parameters:
#    babdelaura_user.example.class: Babdelaura\UserBundle\Example

services:
#    babdelaura_user.example:
#        class: %babdelaura_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
