parameters:
#    babdelaura_blog.example.class: Babdelaura\BlogBundle\Example

services:
    babdelaura_blog.twig_intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
