parameters:
#    babdelaura_blog.example.class: Babdelaura\BlogBundle\Example

services:
    babdelaura_blog.twig_intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    babdelaura_blog.listener.constroller:
        class: Babdelaura\BlogBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
