babdelaurablog_admin_ajouterPageInterne:
    path: /admin/ajouterPageInterne
    defaults: {_controller: BabdelauraBlogBundle:Page:enregistrerPageInterne}

babdelaurablog_admin_afficherPage:
    path: /admin/page/{slug}
    defaults: {_controller: BabdelauraBlogBundle:Page:afficherPageAdmin}

babdelaurablog_admin_modifierPageInterne:
    path: /admin/modifierPageInterne/{slug}
    defaults: {_controller: BabdelauraBlogBundle:Page:enregistrerPageInterne}

babdelaurablog_admin_listerPages:
    path: /admin/pages
    defaults: {_controller: BabdelauraBlogBundle:Page:listerToutesPagesAdmin}

babdelaurablog_admin_publierPage:
    path: /admin/publierPage/{slug}
    defaults: {_controller: BabdelauraBlogBundle:Page:publierPage}

babdelaurablog_admin_supprimerPage:
    path: /admin/supprimerPage/{slug}
    defaults: {_controller: BabdelauraBlogBundle:Page:supprimerPage}
