babdelaurablog_admin_listerImages:
    path: /admin/gallerie
    defaults: {_controller: BabdelauraBlogBundle:Image:listerImages}

babdelaurablog_admin_uploaderImage:
    path: /admin/uploadImage/{addWatermark}
    defaults: {_controller: BabdelauraBlogBundle:Image:upload, addWatermark: true}

