babdelaurablog_admin_listerImages:
    path: /admin/galleriepopup
    defaults: {_controller: BabdelauraBlogBundle:Image:listerImages}

babdelaurablog_admin_gallerieImages:
    path: /admin/gallerie
    defaults: {_controller: BabdelauraBlogBundle:Image:listerImages}

babdelaurablog_admin_uploaderImage:
    path: /admin/uploadImage
    defaults: {_controller: BabdelauraBlogBundle:Image:upload}
