babdelaurablog_admin_gallerieImages:
    path: /admin/gallerie
    defaults: {_controller: BabdelauraBlogBundle:Image:afficherGallerie}

babdelaurablog_admin_getImages:
    path: /admin/getImages
    defaults: {_controller: BabdelauraBlogBundle:Image:getImages}

babdelaurablog_admin_uploaderImage:
    path: /admin/uploadImage
    defaults: {_controller: BabdelauraBlogBundle:Image:upload}
