babdelaurablog_admin_galerieImages:
    path: /admin/galerie
    defaults: {_controller: BabdelauraBlogBundle:Image:affichergalerie}

babdelaurablog_admin_getImages:
    path: /admin/getImages
    defaults: {_controller: BabdelauraBlogBundle:Image:getImages}

babdelaurablog_admin_uploaderImage:
    path: /admin/uploadImage
    defaults: {_controller: BabdelauraBlogBundle:Image:upload}
