babdelaurablog_admin_listerTags:
    path: /admin/tags
    defaults: {_controller: BabdelauraBlogBundle:Tag:listerTousTags}

babdelaurablog_admin_ajouterTag:
    path: /admin/ajouterTag
    defaults: {_controller: BabdelauraBlogBundle:Tag:enregistrerTag}

babdelaurablog_admin_modifierTag:
    path: /admin/modifierTag/{slug}
    defaults: {_controller: BabdelauraBlogBundle:Tag:enregistrerTag}

babdelaurablog_admin_supprimerTag:
    path: /admin/supprimerTag/{slug}
    defaults: {_controller: BabdelauraBlogBundle:Tag:supprimerTag}

babdelaurablog_admin_listerTagsAutocomplete:
    path: /admin/tags-autocomplete
    defaults: {_controller: BabdelauraBlogBundle:Tag:getTags}
