babdelaura_user:
    resource: "@BabdelauraUserBundle/Resources/config/routing.yml"
    prefix:   /

babdelaura_blog:
    resource: "@BabdelauraBlogBundle/Resources/config/routing/blog.yml"
    prefix:   /

babdelaura_admin:
    resource: "@BabdelauraAdminBundle/Resources/config/routing/admin.yml"
    prefix:   /

babdelaura_adminArticle:
    resource: "@BabdelauraAdminBundle/Resources/config/routing/article.yml"
    prefix:   /

babdelaura_adminCategorie:
    resource: "@BabdelauraAdminBundle/Resources/config/routing/categorie.yml"
    prefix:   /

babdelaura_adminCommentaire:
    resource: "@BabdelauraAdminBundle/Resources/config/routing/commentaire.yml"
    prefix:   /

babdelaura_adminImage:
    resource: "@BabdelauraAdminBundle/Resources/config/routing/image.yml"
    prefix:   /

babdelaura_adminPage:
    resource: "@BabdelauraAdminBundle/Resources/config/routing/page.yml"
    prefix:   /

babdelaura_adminTag:
    resource: "@BabdelauraAdminBundle/Resources/config/routing/tag.yml"
    prefix:   /

#ohinstagrambundle:
#    resource: "@OhInstagramBundle/Resources/config/routing.yml"
#    prefix:   /
