babdelaurablog_admin_galerieImages:
    path: /admin/galerie
    defaults: {_controller: BabdelauraAdminBundle:Image:afficherGalerie}

babdelaurablog_admin_getImages:
    path: /admin/getImages
    defaults: {_controller: BabdelauraAdminBundle:Image:getImages}

babdelaurablog_admin_uploaderImage:
    path: /admin/uploadImage
    defaults: {_controller: BabdelauraAdminBundle:Image:upload}
