<?php

namespace Babdelaura\BlogBundle\Repository;

/**
 * InstagramPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstagramPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
